"""empty message

Revision ID: 191ce677f683
Revises: b2c67ee9c49
Create Date: 2015-02-12 13:26:26.472677

"""

# revision identifiers, used by Alembic.
revision = '191ce677f683'
down_revision = 'b2c67ee9c49'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secret_key', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'secret_key')
    ### end Alembic commands ###
