"""empty message

Revision ID: 2693d64d08b6
Revises: 5678f0574a6d
Create Date: 2015-01-23 10:43:13.085148

"""

# revision identifiers, used by Alembic.
revision = '2693d64d08b6'
down_revision = '5678f0574a6d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_idx', table_name='attributes')
    op.create_index('name_idx', 'attributes', ['site_id', 'resource_name', 'name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_idx', table_name='attributes')
    op.create_index('name_idx', 'attributes', ['site_id', 'name'], unique=1)
    ### end Alembic commands ###
