"""empty message

Revision ID: b2c67ee9c49
Revises: 2693d64d08b6
Create Date: 2015-01-27 18:39:56.448966

"""

# revision identifiers, used by Alembic.
revision = 'b2c67ee9c49'
down_revision = '2693d64d08b6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attributes', sa.Column('constraints', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attributes', 'constraints')
    ### end Alembic commands ###
